scalaSource in Compile := baseDirectory.value / "src"
scalaSource in Test := baseDirectory.value / "test"
libraryDependencies += "org.scalatest" %% "scalatest" % "3.2.15"
libraryDependencies += "org.typelevel" %% "cats-effect" % "3.5.5"
libraryDependencies += "org.typelevel" %% "munit-cats-effect-3" % "1.0.6" % "test"
scalaVersion := "3.3.3"